### ISSUE TITLE
Ordering Search Results with Multiple Parameters Doesn't Seem to Work

### ISSUE THREAD

**Issue by javanigus** [keithws/contentful-sync-cli#1]
Hi  @keithws,

I'm trying to order the returned entries by multiple parameters (fields.type, fields.name) but it seems to only sort by the first parameter (fields.type). Is my syntax incorrect or is this a bug? Following is a code snippet 

`module.exports = client.getEntries({
	content_type: "resource",
	order: "fields.type, fields.name"
}).then`

**Comment by keithws** [comment]
Fixed in version 2.1.3 on May 19, 2017.
